stages:
  - test
  - deploy

test:integration-test-for-p2p-network:
  stage: test 
  tags:
    - preloaded-ubuntu1804 
  script:
    - ./scripts/install_bnfc.sh
    - sudo sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/docker:publishLocal
    - sudo python3.6 -m pip install argparse docker pexpect requests
    - sudo ./scripts/p2p-test-tool.py -b -p 1

test:integration-test-for-artifact-creation:
  stage: test 
  tags:
    - preloaded-ubuntu1804 
  script:
    - ./scripts/install_bnfc.sh
    - sudo sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/rpm:packageBin node/debian:packageBin node/universal:packageZipTarball 

deploy:deploy-rnode-artifacts:
  stage: deploy 
  tags:
    - preloaded-ubuntu1804 
  script:
    - ./scripts/install_bnfc.sh
    # docker image to docker hub
    - sudo sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/docker:publishLocal
    - echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin
    - sudo docker tag  coop.rchain/rnode:latest rchain/rnode:${CI_COMMIT_REF_NAME}
    - sudo docker push rchain/rnode:${CI_COMMIT_REF_NAME}

    # deb/rpm packages and compressed archive 
    - sudo sbt -Dsbt.log.noformat=true clean rholang/bnfc:generate node/rpm:packageBin node/debian:packageBin node/universal:packageZipTarball 
    - set -eo pipefail
    - apt update && apt -y install openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - artifacts_dir=$(mktemp -d /tmp/artifacts_out.XXXXXXXX)
    - cp node/target/rnode_*_all.deb ${artifacts_dir}/rnode.deb
    - cp node/target/rpm/RPMS/noarch/rnode-*.noarch.rpm ${artifacts_dir}/rnode.rpm
    - cp rosette/build.out/rosette-*.deb ${artifacts_dir}/rosette.deb
    - rsync -avrz --delete -e  "ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ${artifacts_dir}/* inbound@dispatch.rchain.coop:/home/inbound/cd/artifacts/${CI_COMMIT_REF_NAME}/
  only:
    - master
    - dev
    - gitlab-test
